"""Константы приложения recipes."""

TAG_NAME_MAX_LENGTH = 32
TAG_SLUG_MAX_LENGTH = 32

INGREDIENT_NAME_MAX_LENGTH = 128
MEASUREMENT_UNIT_MAX_LENGTH = 64

RECIPE_NAME_MAX_LENGTH = 256
SHORT_CODE_MAX_LENGTH = 16
SHORT_CODE_GENERATION_ATTEMPTS = 10
MIN_COOKING_TIME = 1

MIN_AMOUNT = 1
